import { _Image } from '@/core/constant/asset'
import { Product } from '@/features/product/types'

/**
 * Mock data for products in the flash sale
 */
export const mockProducts: Product[] = [
  {
    id: 1,
    image: _Image.product,
    topLabel: 'mall' as const,
    bottomLabel: 'cheaper' as const,
    title: 'Thức ăn hạt Classic Pet vị bò cho chó trưởng thành gói 400g',
    originalPrice: 24000,
    discountPercent: 50,
    currentPrice: 12000,
    rating: 5.0,
    sold: 12,
    total: 18,
    timeRemaining: '01:42:00',
    buttonText: '21:00 - Nhắc tôi',
  },
  {
    id: 2,
    image: _Image.product,
    topLabel: 'favorite' as const,
    bottomLabel: 'stable' as const,
    title: 'Thức ăn hạt Royal Canin cho chó con gói 1.5kg',
    originalPrice: 350000,
    discountPercent: 30,
    currentPrice: 245000,
    rating: 4.8,
    sold: 8,
    total: 15,
    timeRemaining: '02:15:30',
    buttonText: '19:00 - Nhắc tôi',
  },
  {
    id: 3,
    image: _Image.product,
    topLabel: null,
    bottomLabel: 'cheaper' as const,
    title: 'Pate cho mèo Whiskas gói 400g',
    originalPrice: 45000,
    discountPercent: 40,
    currentPrice: 27000,
    rating: 4.5,
    sold: 20,
    total: 25,
    timeRemaining: '00:30:15',
    buttonText: '00:00 - Nhắc tôi',
  },
  {
    id: 4,
    image: _Image.product,
    topLabel: 'mall' as const,
    bottomLabel: null,
    title: 'Đồ chơi cho chó mèo bóng tennis cao cấp',
    originalPrice: 150000,
    discountPercent: 25,
    currentPrice: 112500,
    rating: 4.9,
    sold: 5,
    total: 10,
    timeRemaining: '03:20:45',
    buttonText: '02:00 - Nhắc tôi',
  },
  {
    id: 5,
    image: _Image.product,
    topLabel: null,
    bottomLabel: 'stable' as const,
    title: 'Cát vệ sinh cho mèo Ever Clean gói 10L',
    originalPrice: 280000,
    discountPercent: 20,
    currentPrice: 224000,
    rating: 4.7,
    sold: 15,
    total: 20,
    timeRemaining: '01:10:20',
    buttonText: '21:00 - Nhắc tôi',
  },
  {
    id: 6,
    image: _Image.product,
    topLabel: 'favorite' as const,
    bottomLabel: 'cheaper' as const,
    title: 'Thức ăn hạt Pedigree cho chó lớn gói 3kg',
    originalPrice: 420000,
    discountPercent: 35,
    currentPrice: 273000,
    rating: 4.6,
    sold: 10,
    total: 15,
    timeRemaining: '02:45:10',
    buttonText: '19:00 - Nhắc tôi',
  },
]
